### ISSUE TITLE
Login Page Tablet Mode

### ISSUE THREAD

**Issue by putralangkat97** [indrijunanda/RuangAdmin#5]
Sebelumnya terima kasih atas template gratis nya..
saya menemukan masalah di login.html ketika width nya 768px / tablet mode.
.
terima kasih.
![image](https://user-images.githubusercontent.com/53550803/93550419-8ed52c80-f995-11ea-840a-0305b9c58e1f.png)

**Comment by fdciabdul** [comment]
bisa di cek html code nya ?

kemungkinan ada tag div yang kehapus

**Comment by indrijunanda** [comment]
oke mas, terima kasih sudah ngasih tau bugnya, maaf sebelumnya saya baru baca 😁 .
sudah saya benerin bug nya ya mas, 
terima kasih sudah menggunakan template kami 😁
